### PR TITLE
Xc functionals

### PR DESCRIPTION
**Pull request by Mdmorshadurrahman**
further XC_functionals featured

### CODE REVIEW

**Comment by ondracka** [comment]
I have no idea how you managed to put your changes into the "Parse the md temperature" commit, and also how you added some random git module which you only remove in the later commit. Squashing this two together should hopefully keep the history reasonably clean. Worst case I'll clean it manually and overwrite the history.

For the future, before creating pull request from the github, make sure that the branch is not behind the ondracka:master (now it says "This branch is 2 commits ahead, 1 commit behind ondracka:master.") The commits ahead are expected but the 1 commit behind is not.

**Comment by ondracka** [comment]
Correct me if I'm wrong, but at this point I'm suspecting you spend more time fighting with the git than doing the actual coding. Maybe you could take a quick break from the parser and just watch some git videos, or read some git guides. This page is also quite interesting: https://ohmygit.org/  I'm OK of you spend few of your working hours with this is it will help to reduce the problems with the pull requests in the long run. Or as always, I'm happy to help, just let me know what you are fighting with.

**Comment by Mdmorshadurrahman** [comment]
It's true that i am struggling with git but i guess it because of visual studio where i am using git commands, i know basic commands and what is the usage of those but i am having issues because of vscode. Thanks a lot for your link i will definitely study that first. And off-topic, my salary issue has not fixed yet, this month i also got the same amount.

**Comment by ondracka** [comment]
I think the issue is with VS Code default pull behavior. I think you need to set it up so that the `git pull` actually does `git fetch ondracka && git rebase ondracka/master`, with the important part here being the rebase! So try to configure git (or VSCode) to do the rebase by default, quick googling found this, maybe it will help: https://stackoverflow.com/questions/63001513/how-to-discover-the-current-default-behavior-for-git-pull

**Pull request merged**
